# Порт сервера
server.port=8081

# Kafka настройки
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Название топика
kafka.topic.user-events=user-events

# Email настройки (Gmail)
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=roman.emelyanov2017@yandex.ru
spring.mail.password=ihqjtqxqhpuzclzw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.protocol=smtps